### ISSUE TITLE
Allow --parseable flag for npm audit to be used 

### ISSUE THREAD

**Issue by kellymoore** [naugtur/npm-audit-resolver#46]
It would be nice to be able to use the `--parseable` flag so that we can print out the results in pipelines. Currently when passing this flag down, the `--json` flag is still used and we get the following output:

```
➜  npx npm-audit-resolver --parseable
npx: installed 59 in 6.358s
>>>> npm audit --json --parseable
>>>> exit: 1
failed to parse output
update	lodash	high	npm update lodash --depth 7	Command Injection	https://npmjs.com/advisories/1673	node-cache>lodash	N


SyntaxError: Unexpected token i in JSON at position 0
    at JSON.parse (<anonymous>)
```

**Comment by naugtur** [comment]
Can you explain what you're trying to accomplish?

**Comment by kellymoore** [comment]
@naugtur the ability to run `npm-audit-resolver` with the `--parseable` flag as can be done with `npm audit --parseable`. The problem is `--json` is appended by default and overrides this, causing the error I've pasted above

**Comment by naugtur** [comment]
I understand what you're trying to run. I don't understand what for. Need wider context and an example. 

If we define the request as "make passing --parseable work" my response is it's impossible, because npm-audit-resolver consumes json from npm audit and without it, all functionality is gone.

Please share what you're trying to accomplish and any context you find relevant

**Comment by naugtur** [comment]
@kellymoore I do want to help you. Please help me help you ;)
